// React/src/App.js
import 'devextreme/dist/css/dx.light.css';
import 'devexpress-gantt/dist/dx-gantt.min.css';
import React from 'react';

import Gantt, {
  Tasks, Dependencies, Resources, ResourceAssignments, Column,
} from 'devextreme-react/gantt';

import {
  tasks, dependencies, resources, resourceAssignments,
} from './data.js';

function App() {
  return (
    <Gantt
      height={250}
      width={800}
      rootValue={-1}>

      <Tasks dataSource={tasks} />
      <Dependencies dataSource={dependencies} />
      <Resources dataSource={resources} />
      <ResourceAssignments dataSource={resourceAssignments} />

      <Column dataField="title" caption="Subject" width={300} />
      <Column dataField="start" caption="Start Date" />
      <Column dataField="end" caption="End Date" />
    </Gantt>
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { DxGanttModule } from 'devextreme-angular';
import {
  Service, Task, Dependency, Resource, ResourceAssignment,
} from './app.service';

@Component({
    selector: 'app-root',
    imports: [DxGanttModule],
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css'],
    providers: [Service],
})
export class AppComponent {
  tasks: Task[];

  dependencies: Dependency[];

  resources: Resource[];

  resourceAssignments: ResourceAssignment[];

  constructor(service: Service) {
    this.tasks = service.getTasks();
    this.dependencies = service.getDependencies();
    this.resources = service.getResources();
    this.resourceAssignments = service.getResourceAssignments();
  }
}

<dx-gantt [height]="250" [width]="800" [rootValue]="-1">
  <dxo-tasks
    [dataSource]="tasks"
    parentIdExpr="parentId"
    keyExpr="id"
  ></dxo-tasks>
  <dxo-dependencies [dataSource]="dependencies"></dxo-dependencies>
  <dxo-resources [dataSource]="resources"></dxo-resources>
  <dxo-resource-assignments
    [dataSource]="resourceAssignments"
  ></dxo-resource-assignments>
  <dxi-column dataField="title" caption="Subject" [width]="300"></dxi-column>
  <dxi-column
    dataField="start"
    caption="Start Date"
    dataType="date"
  ></dxi-column>
  <dxi-column dataField="end" caption="End Date" dataType="date"></dxi-column>
</dx-gantt>
